name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: denolib/setup-deno@master
      with:
        deno-version: 1.4.2
    - name: Run linter
      run: |
        deno lint --unstable
        deno fmt --check
    - name: Check mod.ts
      run: |
        deno run mod.ts
    - name: Run tests
      run: |
        make test
